version: '3.1'

services:

  elasticsearch:
   container_name: els
   image: elasticsearch:8.13.0 #указывается путь к докер образу (не качало из за ограничений)
   ports:
    - 9200:9200
   volumes:
     - elasticsearch-data:/usr/share/elasticsearch/data
    #- D:\ESD:/usr/share/elasticsearch/data
   environment:
    - xpack.security.enabled=false
    # - xpack.monitoring.enabled=true
    # - xpack.watcher.enabled=false
    # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
    - elastic

  kibana:
   container_name: kibana
   image: kibana:8.13.0
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   networks:
    - elastic
  
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data: